### PR TITLE
Add operating system

### PR DESCRIPTION
**Pull request by openscript**
Most powerful OS 😀

### CODE REVIEW

**Comment by SemiShogun** [comment]
Ok ok I'll also add arch linux 😂

**Comment by openscript** [comment]
Will you also use it as your main driver? 🤓

**Comment by SemiShogun** [comment]
Yes, I think it would be a good idea to do that

**Comment by SemiShogun** [comment]
By the way, do you know of a way to create a script that automatically installs all the programmer software listed in my setup?

**Comment by openscript** [comment]
Well most package manager can do this. With `pacman` you can export the list with `pacman -Qqe | grep -Fvx "$(pacman -Qqm)"`. Later you can install all the packages from this list again. The problem is, that it doesn't include configuration files.

I usually backup the `/` and `/home` volumes. With `btrfs` it's quite easy to make snapshots: https://fedoramagazine.org/btrfs-snapshots-backup-incremental/

**Comment by SemiShogun** [comment]
Wow that's amazing! I can't wait to try it out with arch linux 😁

**Pull request merged**
